version: '3.1'

services:
  db_postgres:
    image: postgres
    restart: always
    ports:
      - 6000:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: list_me

  adminer:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 6001:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    links:
      - db_postgres
